# Generated by Django 4.2.16 on 2024-10-06 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('type', models.CharField(choices=[('Acte', 'Acte'), ('Contrat', 'Contrat'), ('Facture', 'Facture'), ('Rapport', 'Rapport')], max_length=100, verbose_name='Type de document')),
                ('date', models.DateField(verbose_name="Date d'enregistrement")),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Payé', 'Payé'), ('Notarié', 'Notarié'), ('Archivé', 'Archivé')], max_length=100, verbose_name='Statut du document')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('numero_reference', models.CharField(max_length=50, unique=True, verbose_name='Numéro de référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier associé')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_demandeur', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('secretaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_secretaire', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=100, unique=True, verbose_name='Numéro du reçu')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif du paiement')),
                ('date_recu', models.DateField(verbose_name='Date de réception')),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Carte bancaire', 'Carte bancaire'), ('Virement', 'Virement'), ('Chèque', 'Chèque')], max_length=50, verbose_name='Mode de paiement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description supplémentaire')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='notariat.document', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
            ],
        ),
    ]
