# Generated by Django 4.2.16 on 2024-10-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notariat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
    ]
