# Generated by Django 4.2.16 on 2024-10-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notariat', '0002_alter_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recu',
            name='numero_recu',
        ),
    ]
