# Generated by Django 4.2.16 on 2024-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notariat', '0004_alter_recu_date_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recu',
            name='numero_recu',
            field=models.CharField(default='REC-00000', max_length=100, unique=True, verbose_name='Numéro du reçu'),
            preserve_default=False,
        ),
    ]
